### ISSUE TITLE
Request for input data format example

### ISSUE THREAD

**Issue by lipingcoding** [machinelearning4health/MedPath#4]
I understand the privacy concern, but would you like to provide an input data format example, which would help users a lot!
Thanks!

**Comment by machinelearning4health** [comment]
Thank you for your suggestion. We are working on providing the input data format examples. Thank you for your patience!

**Comment by machinelearning4health** [comment]
A sample graph data is uploaded at sample_data/test.graph.adj.sample.pk. Thanks!
